### ISSUE TITLE
Add `IP` type to ipam group

### ISSUE THREAD

**Issue by afritzler** [onmetal/onmetal-api#363]
# Summary

As the described in the new networking API proposal https://github.com/onmetal/onmetal-api/blob/docs/proposal/network-integration/docs/proposals/01-networking-integration.md we need to add  an `IP` type to our API.

## Basic example

```
apiVersion: ipam.onmetal.de/v1alpha1
kind: IP
metadata:
  namespace: default
  name: my-ip
spec:
  # ip: 10.0.0.1 # This gets patched in once allocated
  prefixRef:
    name: my-sub-prefix
  # prefixSelector:
  #   matchLabels:
  #     foo: bar
status:
  conditions:
    - type: Ready
      status: False # This will be set to true once successfully allocated.
      reason: Pending
```

## Definition of done

- `IP` type definition + adding it to the `registry`
- Basic validation and validation tests
