### ISSUE TITLE
Introduce EmptyDisk for the Volumes

### ISSUE THREAD

**Issue by hardikdr** [onmetal/onmetal-api#382]
# Summary
As we discussed, a field EmptyDisk in Machine, similar to the behavior of emptyDir in Kubernetes, would be nice to have. 

## Basic example

```yaml
  volumeAttachments:
    - name: disk1
      priority: 1 # optional
      emptyDisk:
          sizeLimit: 1G
```
## Motivation

EmptyDisk should help order Ephemeral volumes in the vm-cluster.
