### ISSUE TITLE
Applying a machine with different volumes causes devices to be rearranged

### ISSUE THREAD

**Issue by adracus** [onmetal/onmetal-api#522]
**Describe the bug**
When using `kubectl apply` / apply in general and altering volumes of a machine, the resulting
update will zero the values of `device`, causing device names to be rearranged.

**To Reproduce**
1. Create machine

```yaml
apiVersion: compute.api.onmetal.de/v1alpha1
kind: Machine
metadata:
  name: my-machine
spec:
  image: gardenlinux
  machineClassRef:
    name: small
  volumes:
  - name: v1
    emptyDisk: {}
  - name: v2
    emptyDisk: {}
```

Volume `v1` should have device `vdb` and volume `v2` should have `vdc`.

Apply the following machine

```yaml
apiVersion: compute.api.onmetal.de/v1alpha1
kind: Machine
metadata:
  name: my-machine
spec:
  image: gardenlinux
  machineClassRef:
    name: small
  volumes:
  - name: v2
    emptyDisk: {}
  - name: v3
    emptyDisk: {}
```

Now, `v2` has device `vdb` and `v3` has `vdc`.

**Expected behavior**
After the final apply, `v2` should still have `vdc` and `v3` should get `vdb`.
