### ISSUE TITLE
`Network` should have a `spec.providerID` + `status.state`

### ISSUE THREAD

**Issue by adracus** [onmetal/onmetal-api#529]
# Summary

Currently, the identity of a `Network` is solely determined by its `name` / `uid`.
If a provider however chooses to have a different mapping underneath, another storage has to be used to map a
`Network` to a provider representation (e.g. currently for our controllers via annotation).
This causes e.g. `ori` implementors to require access to the source k8s cluster to read the annotation which is not desirable.

To keep things explicit and fix this issue, we should have the `providerID` of a `Network` as a first class field.
The `providerID` should be in the `spec` and immutable once set.
The `state` should be in the `status` and report whether the `Network` configuration is valid.

Example expected manifest:
```yaml
apiVersion: networking.api.onmetal.de/v1alpha1
kind: Network
metadata:
  name: my-network
spec:
  providerID: foobar
status:
  state: Available
```

# Definition of Done

* The `networking` / `v1alpha1` types have been updated
* There is `validation` and tests for the new fields (take inspiration from the `Volume` types how lenient the validation should be)
* The `registry` has been updated
* The `tableconvertor` has been updated
* The api server has been run locally and the developer has verified that the types manually work as expected.
