### ISSUE TITLE
Assign a Public IP to the Loadbalancer.Status

### ISSUE THREAD

**Issue by hardikdr** [onmetal/onmetal-api#560]
# Summary
A public IP from the pool should be assigned to the Loadbalancer.

## Basic example

```yaml
status:
  ips:
    - 45.86.152.88
    - 2001::
```
